export const LOGIN_USER="LOGIN_USER";
export const LOGOUT_USER="LOGOUT_USER";
export const ONLINE_USER="ONLINE_USER";
export const INTERACT_LIKED="INTERACT_LIKED";
export const INTERACT_MATCHED="INTERACT_MATCHED";
export const DISABLED_USER="DISABLED_USER";
